### ISSUE TITLE
ImportError: No module named clickhouse_driver

### ISSUE THREAD

**Issue by davidalanreid** [ssc-oscar/oscar.py#23]
I'm trying to use oscar.py on da2 or da4. After cloning oscar.py, I ran
easy_install --user --upgrade oscar.
When I try to run anything that imports from oscar, I get the following error message:
Traceback (most recent call last):
  File "simple.py", line 1, in <module>
    from oscar import Blob
  File "/home/dreid6/oscar.py/oscar.py", line 6, in <module>
    import clickhouse_driver as clickhouse
ImportError: No module named clickhouse_driver

**Comment by user2589** [comment]
Clickhouse is used for date filtering of commits. It was recently added to Oscar, but package dependencies and imports were not properly introduced. As a quick fix, you can install clickhouse driver:

    pip install --user clickhouse-driver

A more long term fix will be implemented soon

**Comment by davidalanreid** [comment]
Thanks, that fixed it.
Another question: I'm not getting any data back for any query. For example, I copied the following from the tutorial. You can see that both calls return an empty set. Using ~lookup/getValues returns good data.

>>> from oscar import Author
>>> Author('"Albert Krawczyk" <pro-logic@optusnet.com.au>').commit_shas
()
>>> 
>>> from oscar import Commit
>>> Commit('17abdbdc90195016442a6a8dd8e38dea825292ae').changed_file_names
()

**Comment by dkennard3** [comment]
Hello there!

I've done some testing on this issue, and I found that you might be experiencing a KeyError in regards to not having any information pulled up for the Author() call you are making. I've added an `except KeyError` statement in my version of oscar.py that raises an ObjectNotFound error in the main `read_tch` function to see if it was indeed a KeyError: 

```
>>> from oscar import Author
>>> Author('"Albert Krawczyk" pro-logic@optusnet.com.au').commit_shas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "oscar.py", line 267, in wrapper
    setattr(self, key, func(self))
  File "oscar.py", line 1493, in commit_shas
    return slice20(self.read_tch('author_commits', silent=True))
  File "oscar.py", line 430, in read_tch
    return read_tch(self.resolve_path(dtype), self.key, silent)
  File "oscar.py", line 366, in read_tch
    raise ObjectNotFound(path + " " + key)
oscar.ObjectNotFound: '/da0_data/basemaps/a2cFullR.16.tch "Albert Krawczyk" pro-logic@optusnet.com.au'
```

I then checked the gzip file (.s) version of this particular file to see if this author's email was in that file: 
```
[dkennard@da0]~% zcat /da0_data/basemaps/gz/a2cFullR16.s | grep 'pro-logic@optusnet.com.au'
Albert Krawczyk <pro-logic@optusnet.com.au>;0b9cb77d08b30bcd046cdf1effbff4aeac8183e7
Albert Krawczyk <pro-logic@optusnet.com.au>;204db45cd0040a92f9641aa8ea3864279abf1f24
Albert Krawczyk <pro-logic@optusnet.com.au>;217eae418ce6da41463ff5edab55d93c91ed8018`
.....
```

The difference here, from what I can tell, is that you were forgetting to use angle brackets around the author's email. The typical format for an author's name is `'author_name <email>'`. Sometimes there is no name associated with the email and just appears as a space -- `' <email>'`.

Fixing the formatting of the full author string returns the appropriate data: 
```
>>> from oscar import Author
>>> Author('Albert Krawczyk <pro-logic@optusnet.com.au>').commit_shas
('0b9cb77d08b30bcd046cdf1effbff4aeac8183e7', '204db45cd0040a92f9641aa8ea3864279abf1f24', '217eae418ce6da41463ff5edab55d93c91ed8018', ...)
```

In regards to the Commit() call, I'm getting data back when I run this on da0 server:
```
>>> from oscar import Commit
>>> Commit('17abdbdc90195016442a6a8dd8e38dea825292ae').changed_file_names
('29/1876a86e7c4f2feffd7fc643391b5ce1b0b81c',)
>>> Commit('17abdbdc90195016442a6a8dd8e38dea825292ae').blob_shas_rel
('cb41d5c5e84b6f634d7490cbe8eb22767c437268',)
>>> Commit('17abdbdc90195016442a6a8dd8e38dea825292ae').child_shas
('72d8e3ce6c22ee9c7051041bc218bedb64aa2a5d',)
>>> Commit('17abdbdc90195016442a6a8dd8e38dea825292ae').parent_shas
('d94c406a677f4986fd6499e6169c28658e09f63c',)
....
```

Assuming that you were also making these calls on da0 server, it wouldn't make sense how I could get information back and you couldn't. In my personal experience, whenever I received empty data, it usually had something to do with how the key was formatted. If I didn't use the right key, or was off by one character, then read_tch would not be able to find that key, since that exact key does not exist. I'm not sure if this is the same issue or if there is another underlying issue with your version of oscar.py.

Have you tried other relationships? Are you not receiving any data for any of those other calls as well? 

If you'd like more data to test with, there is a `/da0_data/basemaps/gz/` folder (accessible from all da servers) that have .s files you can print to stdout using the `zcat` command. There are other .s files in `/da2_data/` as well. 

For example, if I wanted more commit shas to test I could run:
```
[dkennard@da0]~% zcat /da0_data/basemaps/gz/c2tAFullQ.0.s | head
00000000000004a9b86e267361898666ede4eaaa;1571928839;CookieHCl <nhc7502@naver.com>
0000000000009c012a4fcfe3b1f1d683163b0768;1556966894;zigui <zigui_ps>
000000000000e437f6dc150daaf0e0e3daa07b3c;1557018511;zigui <zigui_ps>
000000000001b58ef4d6727f61f4d7f8625feb72;1391011578;stripe <>
....
```

If you have any follow up questions I'd be more than happy to help. Hopefully the information I provided has helped in some way.

**Comment by dkennard3** [comment]
Just as an update, I ran those same 2 queries in question (Author() and Commit()) on both da2 and da4 and was able to retrieve information for both function calls.

**Comment by davidalanreid** [comment]
I did a git pull in oscar.py, reran it, and it is working fine. Thanks.
